CREATE TABLE `data_platform_purchase_requisition_item_data`
(
    `Buyer`                                int(12) NOT NULL,
    `PurchaseRequisition`                  int(16) NOT NULL,
    `PurchaseRequisitionItem`              int(6) NOT NULL,
    `PurchaseRequisitionItemCategory`      varchar(4) DEFAULT NULL,
    `PlannedOrder`                         int(16) DEFAULT NULL,
    `PrecedingOrderID`                     int(16) DEFAULT NULL,
    `PrecedingOrderItem`                   int(6) DEFAULT NULL,
    `FollowingOrderID`                     int(16) DEFAULT NULL,
    `FollowingOrderItem`                   int(6) DEFAULT NULL,
    `PurchaseRequisitionReleaseStatus`     varchar(2) DEFAULT NULL,
    `PurchaseRequisitionReleaseDate`       date DEFAULT NULL,
    `PurchaseRequisitionItemText`          varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextByBuyer`   varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextBySeller`  varchar(200) DEFAULT NULL,
    `Product`                              varchar(40) DEFAULT NULL,
    `ProductGroup`                         varchar(9) DEFAULT NULL,
    `RequestedQuantity`                    float(15) DEFAULT NULL,
    `BaseUnit`                             varchar(3) DEFAULT NULL,
    `PurchaseRequisitionPrice`             float(13) DEFAULT NULL,
    `PurchaseRequisitionPriceQuantity`     float(15) DEFAULT NULL,
    `ProductPlannedDeliveryDuration`       int(3) DEFAULT NULL,
    `Organization`                         varchar(4) DEFAULT NULL,
    `Seller`                               int(12) DEFAULT NULL,
    `DeliverFromParty`                     int(12) DEFAULT NULL,
    `DeliverToParty`                       int(12) DEFAULT NULL,
    `IssuingPlant`                         varchar(4) DEFAULT NULL,
    `IssuingPlantStorageLocation`          varchar(4) DEFAULT NULL,
    `ReceivingPlant`                       varchar(4) DEFAULT NULL,
    `ReceivingPlantStorageLocation`        varchar(4) DEFAULT NULL,
    `OrderedQuantity`                      float(15) DEFAULT NULL,
    `DeliveryDate`                         date DEFAULT NULL,
    `CreationDate`                         date DEFAULT NULL,
    `PurchaseRequisitionProcessingStatus`  varchar(2) DEFAULT NULL,
    `PurchaseRequisitionItemCurrency`      varchar(5) DEFAULT NULL,
    `MRPArea`                              varchar(10) DEFAULT NULL,
    `MRPController`                        varchar(3) DEFAULT NULL,
    `StockConfirmationPartnerFunction`     varchar(40) DEFAULT NULL,
    `StockConfirmationBusinessPartner`     int(12) DEFAULT NULL,
    `StockConfirmationPlant`               varchar(4) DEFAULT NULL,
    `StockConfirmationPlantBatch`          varchar(10) DEFAULT NULL,
    `Reservation`                          int(16) DEFAULT NULL,
    `ReservationItem`                      int(4) DEFAULT NULL,
    `GLAccount`                            varchar(10) DEFAULT NULL,
    `ItemBlockStatus`                      tinyint(1) DEFAULT NULL,
    `LastChangeDateTime`                   datetime DEFAULT NULL,
    `IsMarkedForDeletion`                  tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Buyer`, `PurchaseRequisition`, `PurchaseRequisitionItem`),

    CONSTRAINT `DataPlatformPurchaseRequisitionItemData_fk` FOREIGN KEY (`Buyer`, `PurchaseRequisition`) REFERENCES `data_platform_purchase_requisition_header_data` (`Buyer`, `PurchaseRequisition`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataPrecedingOrderItem_fk` FOREIGN KEY (`PrecedingOrderID`, `PrecedingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataFollowingOrderItem_fk` FOREIGN KEY (`FollowingOrderID`, `FollowingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataDeliverFromParty_fk` FOREIGN KEY (`DeliverFromParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataIssuingPlant_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataIssuingPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`, `IssuingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReceivingPlant_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReceivingPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`, `ReceivingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPartnerFunction_fk` FOREIGN KEY (`StockConfirmationPartnerFunction`) REFERENCES `data_platform_partner_function_partner_function_data` (`PartnerFunction`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
