CREATE TABLE `data_platform_purchase_requisition_item_data`
(
    `PurchaseRequisition`                               int(16) NOT NULL,
    `PurchaseRequisitionItem`                           int(6) NOT NULL,
    `PurchaseRequisitionItemCategory`                   varchar(4) NOT NULL,
    `SupplyChainRelationshipID`                         int(16) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryID`                 int(6) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryPlantID`            int(4) DEFAULT NULL,
    `SupplyChainRelationshipStockConfPlantID`           int(4) DEFAULT NULL,
    `SupplyChainRelationshipProductionPlantID`          int(4) DEFAULT NULL,
    `Buyer`                                             int(12) NOT NULL,
    `Seller`                                            int(12) DEFAULT NULL,
    `DeliverToParty`                                    int(12) NOT NULL,
    `DeliverFromParty`                                  int(12) DEFAULT NULL,
    `DeliverToPlant`                                    varchar(4) NOT NULL,
    `DeliverToPlantStorageLocation`                     varchar(4) DEFAULT NULL,
    `DeliverFromPlant`                                  varchar(4) DEFAULT NULL,
    `DeliverFromPlantStorageLocation`                   varchar(4) DEFAULT NULL,
    `Product`                                           varchar(40) NOT NULL,
    `ProductGroup`                                      varchar(9) DEFAULT NULL,
    `RequestedQuantityInBaseUnit`                       float(15) NOT NULL,
    `RequestedQuantityInDeliveryUnit`                   float(15) NOT NULL,
    `BaseUnit`                                          varchar(3) NOT NULL,
    `DeliveryUnit`                                      varchar(3) NOT NULL,
    `RequestedDeliveryDate`                             date NOT NULL,
    `PlannedOrder`                                      int(16) DEFAULT NULL,
    `PlannedOrderItem`                                  int(6) DEFAULT NULL,
	`ProductionOrder`                                   int(16) DEFAULT NULL,
	`ProductionOrderItem`                               int(6) DEFAULT NULL,
    `PrecedingOrderID`                                  int(16) DEFAULT NULL,
    `PrecedingOrderItem`                                int(6) DEFAULT NULL,
    `FollowingOrderID`                                  int(16) DEFAULT NULL,
    `FollowingOrderItem`                                int(6) DEFAULT NULL,
    `Project`                                           int(16) DEFAULT NULL,
    `WBSElement`                                        int(8) DEFAULT NULL,
    `PurchaseRequisitionItemText`                       varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextByBuyer`                varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextBySeller`               varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemPrice`                      float(13) DEFAULT NULL,
    `PurchaseRequisitionItemPriceQuantity`              int(6) DEFAULT NULL,
    `ProductPlannedDeliveryDuration`                    float(11) DEFAULT NULL,
    `ProductPlannedDeliveryDurationUnit`                varchar(3) DEFAULT NULL,
    `OrderedQuantityInBaseUnit`                         float(15) DEFAULT NULL,
    `OrderedQuantityInDeliveryUnit`                     float(15) DEFAULT NULL,
    `ItemCompleteOrderIsDefined`                        tinyint(1) DEFAULT NULL,
    `TransactionCurrency`                               varchar(5) DEFAULT NULL,
    `MRPArea`                                           varchar(10) DEFAULT NULL,
    `MRPController`                                     varchar(3) DEFAULT NULL,
    `StockConfirmationBusinessPartner`                  int(12) DEFAULT NULL,
    `StockConfirmationPlant`                            varchar(4) DEFAULT NULL,
    `ProductionPlantBusinessPartner`                    int(12) DEFAULT NULL,
    `ProductionPlant`                                   varchar(4) DEFAULT NULL,
    `GLAccount`                                         varchar(10) DEFAULT NULL,
    `CreationDate`                                      date NOT NULL,
    `CreationTime`                                      time NOT NULL,
    `LastChangeDate`                                    date NOT NULL,
    `LastChangeTime`                                    time NOT NULL,
    `IsReleased`                                        tinyint(1) DEFAULT NULL,
    `IsCancelled`                                       tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                               tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`PurchaseRequisition`, `PurchaseRequisitionItem`),

   CONSTRAINT `DPFMPurchaseRequisitionItemData_fk` FOREIGN KEY (`Buyer`, `PurchaseRequisition`) REFERENCES `data_platform_purchase_requisition_header_data` (`Buyer`, `PurchaseRequisition`),
-- CONSTRAINT `DPFMPurchaseRequisitionItemDataPlannedOrderItem_fk` FOREIGN KEY (`PlannedOrder`, `PlannedOrderItem`) REFERENCES `data_platform_planned_order_item_data` (`PlannedOrder`, `PlannedOrderItem`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataProductionOrderItem_fk` FOREIGN KEY (`ProductionOrder`, `ProductionOrderItem`) REFERENCES `data_platform_production_order_item_data` (`ProductionOrder`, `ProductionOrder`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataPrecedingOrderItem_fk` FOREIGN KEY (`PrecedingOrderID`, `PrecedingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataFollowingOrderItem_fk` FOREIGN KEY (`FollowingOrderID`, `FollowingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataDeliverFromParty_fk` FOREIGN KEY (`DeliverFromParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataIssuingPlant_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataIssuingPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`, `IssuingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataReceivingPlant_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataReceivingPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`, `ReceivingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataStockConfirmationPartnerFunction_fk` FOREIGN KEY (`StockConfirmationPartnerFunction`) REFERENCES `data_platform_partner_function_partner_function_data` (`PartnerFunction`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
   CONSTRAINT `DPFMPurchaseRequisitionItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`)
-- CONSTRAINT `DPFMPurchaseRequisitionItemDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
