CREATE TABLE `data_platform_purchase_requisition_item_data`
(
    `PurchaseRequisition`                               int(16) NOT NULL,
    `PurchaseRequisitionItem`                           int(6) NOT NULL,
    `PurchaseRequisitionItemCategory`                   varchar(4) NOT NULL,
    `SupplyChainRelationshipID`                         int(16) DEFAULT NULL,
    `SupplyChainRelationshipDeliveryID`                 int(6) NOT NULL,
    `SupplyChainRelationshipDeliveryPlantID`            int(4) NOT NULL,
    `SupplyChainRelationshipStockConfPlantID`           int(4) DEFAULT NULL,
    `SupplyChainRelationshipProductionPlantID`          int(4) DEFAULT NULL,
    `Buyer`                                             int(12) NOT NULL,
    `Seller`                                            int(12) DEFAULT NULL,
    `DeliverToParty`                                    int(12) NOT NULL,
    `DeliverFromParty`                                  int(12) DEFAULT NULL,
    `DeliverToPlant`                                    varchar(4) NOT NULL,
    `DeliverToPlantStorageLocation`                     varchar(4) DEFAULT NULL,
    `DeliverFromPlant`                                  varchar(4) DEFAULT NULL,
    `DeliverFromPlantStorageLocation`                   varchar(4) DEFAULT NULL,
    `Product`                                           varchar(40) NOT NULL,
    `ProductGroup`                                      varchar(9) DEFAULT NULL,
    `RequestedQuantity`                                 float(15) NOT NULL,
    `BaseUnit`                                          varchar(3) NOT NULL,
    `DeliveryUnit`                                      varchar(3) DEFAULT NULL,
    `PlannedOrder`                                      int(16) DEFAULT NULL,
    `PlannedOrderItem`                                  int(6) DEFAULT NULL,
    `PrecedingOrderID`                                  int(16) DEFAULT NULL,
    `PrecedingOrderItem`                                int(6) DEFAULT NULL,
    `FollowingOrderID`                                  int(16) DEFAULT NULL,
    `FollowingOrderItem`                                int(6) DEFAULT NULL,
    `Project`                                           int(16) DEFAULT NULL,
    `WBSElement`                                        int(8) DEFAULT NULL,
    `PurchaseRequisitionReleaseStatus`                  varchar(2) DEFAULT NULL,
    `PurchaseRequisitionReleaseDate`                    date DEFAULT NULL,
    `PurchaseRequisitionItemText`                       varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextByBuyer`                varchar(200) DEFAULT NULL,
    `PurchaseRequisitionItemTextBySeller`               varchar(200) DEFAULT NULL,
    `PurchaseRequisitionPrice`                          float(13) DEFAULT NULL,
    `PurchaseRequisitionPriceQuantity`                  int(6) DEFAULT NULL,
    `ProductPlannedDeliveryDuration`                    float(11) DEFAULT NULL,
    `ProductPlannedDeliveryDurationUnit`                varchar(3) DEFAULT NULL,
    `OrderedQuantity`                                   int(12) DEFAULT NULL,
    `DeliveryDate`                                      date DEFAULT NULL,
    `PurchaseRequisitionItemStatus`                     varchar(4) DEFAULT NULL,
    `PurchaseRequisitionItemCurrency`                   varchar(4) DEFAULT NULL,
    `MRPArea`                                           varchar(10) DEFAULT NULL,
    `MRPController`                                     varchar(3) DEFAULT NULL,
    `StockConfirmationBusinessPartner`                  int(12) DEFAULT NULL,
    `StockConfirmationPlant`                            varchar(4) DEFAULT NULL,
    `ProductionPlantBusinessPartner`                    int(12) DEFAULT NULL,
    `ProductionPlant`                                   varchar(4) DEFAULT NULL,
    `GLAccount`                                         varchar(10) DEFAULT NULL,
    `ItemBlockStatus`                                   tinyint(1) DEFAULT NULL,
    `CreationDate`                                      date NOT NULL,
    `LastChangeTime`                                    time NOT NULL,
    `IsCancelled`                                       tinyint(1) DEFAULT NULL,
    `IsMarkedForDeletion`                               tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`PurchaseRequisition`, `PurchaseRequisitionItem`),

    CONSTRAINT `DataPlatformPurchaseRequisitionItemData_fk` FOREIGN KEY (`Buyer`, `PurchaseRequisition`) REFERENCES `data_platform_purchase_requisition_header_data` (`Buyer`, `PurchaseRequisition`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataPlannedOrder_fk` FOREIGN KEY (`PlannedOrder`) REFERENCES `data_platform_planned_order_header_data` (`PlannedOrder`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataPrecedingOrderItem_fk` FOREIGN KEY (`PrecedingOrderID`, `PrecedingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataFollowingOrderItem_fk` FOREIGN KEY (`FollowingOrderID`, `FollowingOrderItem`) REFERENCES `data_platform_orders_item_data` (`OrderID`, `OrderItem`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataProduct_fk` FOREIGN KEY (`Product`) REFERENCES `data_platform_product_master_general_data` (`Product`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataProductGroup_fk` FOREIGN KEY (`ProductGroup`) REFERENCES `data_platform_product_group_product_group_data` (`ProductGroup`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataBaseUnit_fk` FOREIGN KEY (`BaseUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataSeller_fk` FOREIGN KEY (`Seller`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataDeliverFromParty_fk` FOREIGN KEY (`DeliverFromParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataDeliverToParty_fk` FOREIGN KEY (`DeliverToParty`) REFERENCES `data_platform_business_partner_general_data` (`BusinessPartner`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataIssuingPlant_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataIssuingPlantStorageLocation_fk` FOREIGN KEY (`DeliverFromParty`, `IssuingPlant`, `IssuingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReceivingPlant_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReceivingPlantStorageLocation_fk` FOREIGN KEY (`DeliverToParty`, `ReceivingPlant`, `ReceivingPlantStorageLocation`) REFERENCES `data_platform_plant_storage_location_data` (`BusinessPartner`, `Plant`, `StorageLocation`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPartnerFunction_fk` FOREIGN KEY (`StockConfirmationPartnerFunction`) REFERENCES `data_platform_partner_function_partner_function_data` (`PartnerFunction`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPlant_fk` FOREIGN KEY (`StockConfirmationBusinessPartner`, `StockConfirmationPlant`) REFERENCES `data_platform_plant_general_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataStockConfirmationPlantBatch_fk` FOREIGN KEY (`Product`, `StockConfirmationBusinessPartner`, `StockConfirmationPlant`, `StockConfirmationPlantBatch`) REFERENCES `data_platform_batch_master_record_batch_data` (`Product`, `BusinessPartner`, `Plant`, `Batch`),
    CONSTRAINT `DataPlatformPurchaseRequisitionItemDataReservationItem_fk` FOREIGN KEY (`Reservation`, `ReservationItem`) REFERENCES `data_platform_reservation_document_item_data` (`Reservation`, `ReservationItem`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
